name: Deploy Dev
on:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_DEV_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Build
        run: |
          pnpm install
          pnpm -r build
      - name: CDK bootstrap & deploy
        run: |
          cd infra
          npx cdk bootstrap
          npx cdk deploy --all --require-approval never -c edgeOnly=true
